[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
